// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SqBelAir4Context))]
    [Migration("20260521000001_AddPostAnalysisFields")]
    partial class AddPostAnalysisFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ConcernReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalLocation")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnName("additional_location")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnName("address")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Anonymous")
                        .HasColumnName("anonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("category")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnName("description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DetectedKeywords")
                        .HasColumnName("detected_keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnName("latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnName("longitude")
                        .HasColumnType("float");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnName("photo")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("priority")
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("medium");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("reference")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReporterContact")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("reporter_contact")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReporterName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("reporter_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnName("street")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnName("is_public")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ConcernReports");
                });

            modelBuilder.Entity("WebApplication1.Models.KeywordDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("category")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Keyword")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("keyword")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnName("language")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("severity")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KeywordDictionaries");
                });

            modelBuilder.Entity("WebApplication1.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("breed")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("color")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("type")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("WebApplication1.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnName("author")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnName("category")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Date")
                        .HasMaxLength(100)
                        .HasColumnName("date")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnName("description")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DetectedKeywords")
                        .HasColumnName("detected_keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Helpful")
                        .HasColumnName("helpful")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnName("image")
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_public")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnName("location")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnName("priority")
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("medium");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnName("title")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WebApplication1.Models.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnName("author")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Date")
                        .HasMaxLength(100)
                        .HasColumnName("date")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnName("description")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PostId")
                        .HasColumnName("post_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("WebApplication1.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("password")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id").HasName("PK__userAcco__3213E83FEB69C83D");

                    b.ToTable("userAccounts");
                });

            modelBuilder.Entity("WebApplication1.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("brand")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("category")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("color")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("model")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("plate_number")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnName("type")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Vin")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnName("vin")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnName("year")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("WebApplication1.Models.Reply", b =>
                {
                    b.HasOne("WebApplication1.Models.Post", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("WebApplication1.Models.Post", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
